# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-04-06 17:25-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: ../rudder.py:118
msgid "bad rudder calibration"
msgstr "mauvais étallonage de la barre"

#: ../rudder.py:122
msgid "bad servo rudder calibration"
msgstr "mauvais étalonnage du servo de barre"

#: ../rudder.py:193
msgid "servo rudder autogain failed"
msgstr "échec du gain automatique du servo de barre"

#: ../failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot a échoué à importer les modules requis. Avez-vous oublié "
"d'exécuter sudo python3 setup.py install ?"

#: ../pyjson.py:14
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"AVERTISSEMENT : la bibliothèque python ujson a échoué, l'analyse consommera "
"plus de ressources"

#: ../servo.py:453
msgid "servo calibration invalid"
msgstr "étalonnage servo invalide"

#: ../servo.py:588
msgid "failed to open servo on:"
msgstr "échec de l'ouverture du servo sur :"

#: ../servo.py:595
msgid "failed set nonblocking/exclusive"
msgstr "échec de l'initialisation du mode non bloquant/exclusif"

#: ../servo.py:626 ../signalk.py:189
msgid "found"
msgstr "trouvé"

#: ../servo.py:743
msgid "loading servo calibration"
msgstr "chargement de l'étalonnage du servo"

#: ../servo.py:747
msgid "WARNING: using default servo calibration!!"
msgstr "ATTENTION : utilisation de l'étalonnage par défaut du servo !!"

#: ../servo.py:756
msgid "probing"
msgstr "recherche"

#: ../servo.py:772
msgid "arduino servo detected"
msgstr "servo arduino détecté"

#: ../servo.py:781
msgid "device needed for option"
msgstr "device nécessaire pour l'option"

#: ../nmea.py:109
msgid "nmea failed to parse gps"
msgstr "nmea a échoué à analyser le gps"

#: ../nmea.py:149
msgid "nmea failed to parse wind"
msgstr "nmea a échoué à analyser le vent"

#: ../nmea.py:211
msgid "exception parsing apb"
msgstr "exception analysant apb"

#: ../nmea.py:253 ../nmea.py:263
msgid "exception parsing vhw"
msgstr "exception en analysant vhw"

#: ../nmea.py:352
msgid "unhandled nmea pipe string"
msgstr "chaîne de caractères nmea non gérée"

#: ../nmea.py:405
msgid "lost serial"
msgstr "série perdue"

#: ../nmea.py:428
msgid "nmea got flag for process pipe:"
msgstr "nmea a reçu un drapeau pour le tube du processus :"

#: ../nmea.py:450
msgid "is another process accessing it?"
msgstr "un autre processus y accède-t-il ?"

#: ../nmea.py:452
msgid "serial device timed out"
msgstr "le périphérique série a expiré"

#: ../nmea.py:521
msgid "failed to open"
msgstr "échec de l'ouverture"

#: ../nmea.py:587
msgid "nmea server on port"
msgstr "serveur nmea sur le port"

#: ../nmea.py:587
msgid "bind failed."
msgstr "la liaison a échoué."

#: ../nmea.py:589
msgid "listening on port"
msgstr "écoute sur le port"

#: ../nmea.py:589
msgid "for nmea connections"
msgstr "pour les connexions nmea"

#: ../nmea.py:660
msgid "nmea server has too many connections"
msgstr "le serveur nmea a trop de connexions"

#: ../nmea.py:686
msgid "nmea client lost connection"
msgstr "le client nmea a perdu la connexion"

#: ../nmea.py:691
msgid "nmea sock not in sockets!"
msgstr "la socket nmea pas dans sockets !"

#: ../nmea.py:702
msgid "nmea failed to unregister socket"
msgstr "nmea a échoué à désinscrire la socket"

#: ../nmea.py:707
msgid "nmea failed to remove fd"
msgstr "nmea a échoué à supprimer fd"

#: ../nmea.py:712
msgid "nmea failed to remove address"
msgstr "nmea a échoué à supprimer l'adresse"

#: ../nmea.py:737
msgid "invalid value"
msgstr "valeur invalide"

#: ../nmea.py:747
msgid "connect error"
msgstr "erreur de connexion"

#: ../nmea.py:776 ../signalk.py:269
msgid "failed to connect"
msgstr "échec de connexion"

#: ../nmea.py:784
msgid "nmea client connected"
msgstr "client nmea connecté"

#: ../nmea.py:813
msgid "poll took too long in nmea process!"
msgstr "le poll a pris trop de temps dans le processus nmea !"

#: ../nmea.py:820
msgid "nmea bridge lost server connection"
msgstr "le pont nmea a perdu la connexion au serveur"

#: ../nmea.py:823
msgid "nmea bridge lost pipe to autopilot"
msgstr "le pont nmea a perdu le tube vers le pilote automatique"

#: ../nmea.py:847
msgid "nmea bridge unhandled poll flag"
msgstr "drapeau de poll non géré par le pont nmea"

#: ../nmea.py:907
msgid "nmea process loop too slow:"
msgstr "boucle du processus nmea trop lente :"

#: ../nonblockingpipe.py:40
msgid "error pipe block on recv!"
msgstr "erreur le tube bloque en réception!"

#: ../nonblockingpipe.py:42
msgid "failed to recv nonblocking pipe!"
msgstr "échec de réception tube non bloquant!"

#: ../nonblockingpipe.py:69
msgid "pipe full"
msgstr "tube plein"

#: ../nonblockingpipe.py:69
msgid "cannot send"
msgstr "ne peut pas envoyer"

#: ../nonblockingpipe.py:89 ../nonblockingpipe.py:145
msgid "failed to decode data socket!"
msgstr "échec de décodage de la socket de données !"

#: ../nonblockingpipe.py:103
msgid "failed to encode data socket!"
msgstr "échec d'encodage de la socket de données !"

#: ../nonblockingpipe.py:155
msgid "failed write"
msgstr "échec d'écriture"

#: ../server.py:106
msgid "ERROR no connections in watch"
msgstr "ERREUR aucune connexion en vue"

#: ../server.py:209
msgid "remove duplicate udp connection"
msgstr "supprimer la connexion udp en double"

#: ../server.py:486
msgid "failed to monitor "
msgstr "échec de surveillance"

#: ../server.py:490
msgid "creating config directory: "
msgstr "création du répertoire de configuration :"

#: ../server.py:497
msgid "failed to load"
msgstr "échec du chargement"

#: ../server.py:508
msgid "backup data failed as well"
msgstr "les données de sauvegarde ont également échoué"

#: ../server.py:570
msgid "failed to write"
msgstr "échec de l'écriture"

#: ../server.py:625
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server : échec de la liaison ; serveur déjà démarré ?"

#: ../server.py:688
msgid "persistent store took too long!"
msgstr "le stockage persistent a pris trop de temps !"

#: ../server.py:706
msgid "max connections reached"
msgstr "max de connexions atteint"

#: ../server.py:709
msgid "server add socket"
msgstr "le serveur a ajouté la socket"

#: ../server.py:719
msgid "internal pipe closed, server exiting"
msgstr "tube interne fermé, serveur se termine"

#: ../server.py:771
msgid "server socket closed from flush!!"
msgstr "socket serveur fermée depuis le cache !!"

#: ../signalk.py:52
msgid "service removed"
msgstr "service supprimé"

#: ../signalk.py:55
msgid "server lost"
msgstr "serveur perdu"

#: ../signalk.py:61
msgid "service add"
msgstr "service ajouté"

#: ../signalk.py:86 ../client.py:210
msgid "failed to"
msgstr "échec de"

#: ../signalk.py:86
msgid "autodetection not possible"
msgstr "détection automatique impossible"

#: ../signalk.py:87 ../signalk.py:176 ../signalk.py:246 ../client.py:211
msgid "try"
msgstr "essayer"

#: ../signalk.py:87 ../signalk.py:176 ../signalk.py:246 ../client.py:211
msgid "or"
msgstr "ou bien"

#: ../signalk.py:138
msgid "read token"
msgstr "lire le token"

#: ../signalk.py:141
msgid "failed to read token"
msgstr "échec de lecture du token"

#: ../signalk.py:171
msgid "probe"
msgstr "recherche"

#: ../signalk.py:175
msgid "could not"
msgstr "n'a pas pu"

#: ../signalk.py:185
msgid "failed to retrieve/parse data from"
msgstr "échec de la récupération/analyse des données de"

#: ../signalk.py:201
msgid "see if token is ready"
msgstr "voir si le token est prêt"

#: ../signalk.py:207
msgid "received token"
msgstr "token reçu"

#: ../signalk.py:213
msgid "failed to store token"
msgstr "échec du stockage du token"

#: ../signalk.py:217 ../signalk.py:238
msgid "error requesting access"
msgstr "erreur lors de la demande d'accès"

#: ../signalk.py:236
msgid "request access url"
msgstr "url de demande d'accès"

#: ../signalk.py:245
msgid "cannot create connection:"
msgstr "impossible de créer la connexion :"

#: ../signalk.py:260
msgid "bad status, rejecting token"
msgstr "mauvais status, token rejeté"

#: ../signalk.py:264
msgid "connection refused"
msgstr "Connexion rejetée"

#: ../signalk.py:313
msgid "server found"
msgstr "serveur trouvé"

#: ../signalk.py:334
msgid "connected to"
msgstr "connecté à"

#: ../signalk.py:416
msgid "Exception converting signalk->pypilot"
msgstr "Exception de la conversion signalk->pypilot"

#: ../signalk.py:430
msgid "received"
msgstr "reçu"

#: ../signalk.py:493
msgid "failed to send updates"
msgstr "échec de l'envoi des mises à jour"

#: ../signalk.py:507
msgid "failed to parse msg:"
msgstr "échec de l'analyse du message :"

#: ../sensors.py:49
msgid "sensor found"
msgstr "capteur trouvé"

#: ../sensors.py:413
msgid "unknown data parsed!"
msgstr "données inconnues analysées !"

#: ../calibration_fit.py:38
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"échec du chargement de la bibliothèque scientifique, impossible d'effectuer "
"la mise à jour de l'étalonnage !"

#: ../calibration_fit.py:701
msgid "Bad Accelerometer Calibration"
msgstr "Mauvais étalonnage de l'accéléromètre"

#: ../calibration_fit.py:735
msgid "magnetic distortions"
msgstr "distorsions magnétiques"

#: ../pilots/__init__.py:22
msgid "ERROR loading"
msgstr "Erreur de chargement"

#: ../autopilot.py:135
msgid "failed to load pilot"
msgstr "échec du chargement du pilote"

#: ../autopilot.py:138
msgid "Available Pilots"
msgstr "Pilotes disponibles"

#: ../autopilot.py:157
msgid "warning: failed to open special file"
msgstr "avertissement : échec de l'ouverture du fichier spécial"

#: ../autopilot.py:157
msgid "for writing"
msgstr "en écriture"

#: ../autopilot.py:158
msgid "cannot stroke the watchdog"
msgstr "erreur de surveillance watchdog"

#: ../autopilot.py:162
msgid "warning: failed to make autopilot process realtime"
msgstr ""
"avertissement : impossible de rendre temps réel le processus autopilot"

#: ../autopilot.py:347
msgid "server/client is running too _slowly_"
msgstr "le serveur/client s'exécute trop _lentement_"

#: ../autopilot.py:353
msgid "sensors is running too _slowly_"
msgstr "les capteurs fonctionnent trop lentement"

#: ../autopilot.py:453
msgid "autopilot routine is running too _slowly_"
msgstr "la séquence du pilote automatique s'exécute trop lentement"

#: ../autopilot.py:465
msgid "servo is running too _slowly_"
msgstr "le servo tourne trop lentement"

#: ../autopilot.py:475
msgid "autopilot iteration running too slow"
msgstr "itération du pilote automatique trop lente"

#: ../autopilot.py:488
msgid "WARNING: running autopilot as root!!"
msgstr "AVERTISSEMENT : le pilote automatique s'exécute en tant que root !!"

#: ../autopilot.py:490
msgid "init complete"
msgstr "initialisation terminée"

#: ../boatimu.py:33
msgid "RTIMU library not detected, please install it"
msgstr "Bibliothèque RTIMU non détectée, veuillez l'installer"

#: ../boatimu.py:57
msgid "Using settings file"
msgstr "Utilisation du fichier de paramètres"

#: ../boatimu.py:97
msgid "ERROR: No IMU Detected"
msgstr "ERREUR : aucune IMU détectée"

#: ../boatimu.py:105
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr ""
"ERREUR : échec de l'initialisation de l'IMU, aucune donnée inertielle "
"disponible"

#: ../boatimu.py:131
msgid "warning, failed to make imu process realtime"
msgstr "avertissement, impossible de remdre temps réel le processus imu"

#: ../boatimu.py:133
msgid "made imu process realtime"
msgstr "a rendu le processus imu temps réel"

#: ../boatimu.py:145
msgid "setting initial gyro bias"
msgstr "réglage du biais initial du gyroscope"

#: ../boatimu.py:161
msgid "imu process failed to keep time"
msgstr "le processus imu a échoué à garder l'heure"

#: ../boatimu.py:169
msgid "failed to read IMU!"
msgstr "échec de la lecture de l'IMU !"

#: ../boatimu.py:202
msgid "imu rate set to rate"
msgstr "taux imu mis à taux"

#: ../boatimu.py:230
msgid "too high standing gyro bias, resetting sensors"
msgstr "biais gyroscopique au repos trop élevé, réinitialisation des capteurs"

#: ../boatimu.py:235
msgid "compass out of range, resetting"
msgstr "compas hors de portée, réinitialisation"

#: ../boatimu.py:327
msgid "warning, failed to make calibration process other"
msgstr "avertissement, impossible de rendre le processus d'étalonnage autre"

#: ../boatimu.py:329
msgid "warning, failed to make calibration process idle, trying renice"
msgstr ""
"avertissement, impossible de rendre le processus d'étalonnage idle, essai de renice"

#: ../boatimu.py:331
msgid "warning, failed to renice calibration process"
msgstr "avertissement, impossible de renice le processus d'étalonnage"

#: ../boatimu.py:338
msgid "calibration loaded, starting"
msgstr "étalonnage chargé, démarrage"

#: ../boatimu.py:342
msgid "failed import calibration fit"
msgstr "échec de l'importation des valeurs d'étalonnage"

#: ../boatimu.py:460
msgid "accel values invalid"
msgstr "valeurs d'accélération invalides"

#: ../bufferedsocket.py:55
msgid "overflow in pypilot udp socket"
msgstr "trop-plein dans la socket udp du pypilot"

#: ../bufferedsocket.py:60
msgid "overflow in pypilot socket"
msgstr "trop-plein dans la socket du pypilot"

#: ../bufferedsocket.py:75
msgid "failed to send udp packet"
msgstr "échec de l'envoi du paquet udp"

#: ../bufferedsocket.py:84
msgid "pypilot socket failed to send to"
msgstr "la socket pypilot a échoué à envoyer à"

#: ../bufferedsocket.py:98
msgid "socket send took too long!?!?"
msgstr "l'envoi par la socket a pris trop de temps !?!?"

#: ../bufferedsocket.py:100
msgid "socket send error"
msgstr "erreur d'envoi de socket"

#: ../bufferedsocket.py:104
msgid "pypilot socket exception"
msgstr "exception de la socket pypilot"

#: ../bufferedsocket.py:108
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr "utilisation de la socket non bloquant python, utilisera plus de ressources"

#: ../bufferedsocket.py:134
msgid "socket send error in server flush"
msgstr "erreur d'envoi par la socket lors du flush du serveur"

#: ../bufferedsocket.py:149
msgid "error receiving data"
msgstr "erreur de réception des données"

#: ../serialprobe.py:30
msgid "error reading"
msgstr "erreur de lecture"

#: ../serialprobe.py:86
msgid "found more devices by path"
msgstr "trouvé plus de périphériques par chemin"

#: ../serialprobe.py:118
msgid "removing gps device"
msgstr "suppresion du périphérique gps"

#: ../serialprobe.py:197
msgid "no pyudev module! will scan usb devices often!"
msgstr "pas de module pyudev ! analysera souvent les périphériques USB !"

#: ../serialprobe.py:359
msgid "success"
msgstr "succès"

#: ../serialprobe.py:367
msgid "failed to record device"
msgstr "échec de l'enregistrement de l'appareil"

#: ../client.py:93
msgid "warning, registering existing value:"
msgstr "avertissement, enregistrement de la valeur existante :"

#: ../client.py:154
msgid "failed to read config file:"
msgstr "échec de la lecture du fichier de configuration :"

#: ../client.py:188
msgid "failed to write config file:"
msgstr "échec de l'écriture du fichier de configuration :"

#: ../client.py:190
msgid "Exception writing config file:"
msgstr "Exception d'écriture du fichier de configuration :"

#: ../client.py:210
msgid "autodetecting pypilot server not possible"
msgstr "détection automatique du serveur pypilot impossible"

#: ../client.py:319
msgid "invalid message from server:"
msgstr "message invalide du serveur :"

#: ../client.py:343
msgid "warning, pypilot client aleady has connection"
msgstr "avertissement, le client pypilot a déjà une connexion"

#: ../client.py:363
msgid "connect failed to"
msgstr "échec de la connexion à"

#: ../client.py:460 ../client.py:463
msgid "failed to connect to"
msgstr "échec de la connexion à"

#: ../client.py:466
msgid "no pypilot server found"
msgstr "aucun serveur pypilot trouvé"

#: ../client.py:522
msgid "usage"
msgstr "utilisation"

#: ../client.py:525
msgid "set the host or ip address"
msgstr "définir l'hôte ou l'adresse IP"

#: ../client.py:526
msgid "print info about each value type"
msgstr "afficher des informations sur chaque type de valeur"

#: ../client.py:527
msgid "continuous watch"
msgstr "veille continue"

#: ../client.py:528
msgid "show this message"
msgstr "afficher ce message"

#: ../client.py:555
msgid "failed to retrieve value list!"
msgstr "échec de la récupération de la liste de valeurs !"

#: ../client.py:566
msgid "timeout retrieving"
msgstr "délai d'attente pour la récupération"

#: ../client.py:569
msgid "missing"
msgstr "manquant"

#: ../values.py:135
msgid "invalid initial value for range property"
msgstr "valeur initiale invalide pour la plage de la propriété"

#: ../values.py:184
msgid "invalid set"
msgstr "ensemble invalide"

#: ../gpsd.py:46
msgid "gpsd connected"
msgstr "gpsd connecté"

#: ../gpsd.py:50
msgid "gpsd failed to connect"
msgstr "gpsd a échoué à se connecter"

#: ../gpsd.py:56
msgid "exception connecting to gps"
msgstr "exception connexion au gps"

#: ../gpsd.py:60
msgid "gpsd disconnected"
msgstr "gpsd déconnecté"

#: ../gpsd.py:74
msgid "gpsd PROBE success"
msgstr "succès de gpsd PROBE"

#: ../gpsd.py:82
msgid "gpsd probe failed"
msgstr "la recherche de gpsd a échoué"

#: ../gpsd.py:105
msgid "gpsd deactivated"
msgstr "gpsd désactivé"

#: ../gpsd.py:147
msgid "gpsd failed to determine serial baud rate of device"
msgstr "gpsd a échoué à déterminer le débit en bauds du périphérique"

#: ../gpsd.py:164
msgid "gpsd timeout from lack of data"
msgstr "délai d'attente gpsd dépassé par manque de données"

#: ../gpsd.py:179
msgid "gpsd received invalid message"
msgstr "gpsd a reçu un message invalide"

#: ../gpsd.py:224
msgid "gpsd got flag for pipe:"
msgstr "gpsd a obtenu un drapeau pour le tube :"

#: ../gpsd.py:233
msgid "gpsd serial probe"
msgstr "sonde série gpsd"

#~ msgid "exception in calibration:"
#~ msgstr "exception dans l'étalonnage :"

#~ msgid "warning: unhandled message"
#~ msgstr "avertissement : message non géré"

#~ msgid "Autopilot Control"
#~ msgstr "Contrôle du pilote automatique"

#~ msgid "AP"
#~ msgstr "AP"

#~ msgid "N/A"
#~ msgstr "N/A"

#~ msgid "        N/A        "
#~ msgstr "        N/A        "

#~ msgid "----"
#~ msgstr "----"

#~ msgid " N/A "
#~ msgstr " N/A "

#~ msgid "port"
#~ msgstr "babord"

#~ msgid "starboard"
#~ msgstr "tribord"

#~ msgid "Pilot"
#~ msgstr "Pilote"

#~ msgid "Compass"
#~ msgstr "Compas"

#~ msgid "GPS"
#~ msgstr "GPS"

#~ msgid "Wind"
#~ msgstr "Vent"

#~ msgid "True Wind"
#~ msgstr "Vent vrai"

#~ msgid "Center"
#~ msgstr "Centre"

#~ msgid "&Scope"
#~ msgstr "&Portée"

#~ msgid "&Client"
#~ msgstr "&Client"

#~ msgid "C&alibration"
#~ msgstr "&Étalonnage"

#~ msgid "Close"
#~ msgstr "Fermer"

#~ msgid "Calibration"
#~ msgstr "Étalonnage"

#~ msgid "Boat is level"
#~ msgstr "Le bateau est à niveau"

#~ msgid "Reset"
#~ msgstr "Réinitialiser"

#~ msgid "Alignment"
#~ msgstr "Alignement"

#~ msgid "Heading"
#~ msgstr "Cap"

#~ msgid "     N/A     "
#~ msgstr "     N/A     "

#~ msgid "Offset"
#~ msgstr "Décalage"

#~ msgid "Coords"
#~ msgstr "Coordonnées"

#~ msgid "Sea"
#~ msgstr "Mer"

#~ msgid "Boat"
#~ msgstr "Bateau"

#~ msgid "Scope"
#~ msgstr "Portée"

#~ msgid "Pitch"
#~ msgstr "Tangage"

#~ msgid "Roll"
#~ msgstr "Roulis"

#~ msgid "Heel"
#~ msgstr "Gîte"

#~ msgid "alignment"
#~ msgstr "alignement"

#~ msgid "Calibration Age"
#~ msgstr "Âge de l'étalonnage"

#~ msgid "Clear"
#~ msgstr "Effacer"

#~ msgid "calibration locked"
#~ msgstr "étalonnage verrouillé"

#~ msgid "accel"
#~ msgstr "accélération"

#~ msgid "Sigma Points"
#~ msgstr "Points Sigma"

#~ msgid "local history"
#~ msgstr "historique local"

#~ msgid "current"
#~ msgstr "actuel"

#~ msgid "Calibration Points"
#~ msgstr "Points d'étalonnage"

#~ msgid "compass"
#~ msgstr "compas"

#~ msgid ""
#~ "Press each button when the rudder is at the correct position to calibrate."
#~ msgstr ""
#~ "Appuyez sur chaque bouton lorsque la barre est dans la bonne position "
#~ "pour l'étalonnage."

#~ msgid "Rudder"
#~ msgstr "Barre"

#~ msgid "Reset Calibration"
#~ msgstr "Réinitialiser l'étalonnage"

#~ msgid "Rudder Is Centered"
#~ msgstr "La barre est centrée"

#~ msgid "------"
#~ msgstr "------"

#~ msgid "Rudder is Starboard Range"
#~ msgstr "La barre est en butée tribord"

#~ msgid "Scale"
#~ msgstr "Echelle"

#~ msgid "Rudder is Port Range"
#~ msgstr "La barre est en butée babord"

#~ msgid "Non Linearity"
#~ msgstr "Non linéarité"

#~ msgid " range +-"
#~ msgstr " variation +-"

#~ msgid "degrees"
#~ msgstr "degrés"

#~ msgid "rudder"
#~ msgstr "barre"

#~ msgid "settings"
#~ msgstr "paramètres"

#~ msgid "failed to load pywavefront:"
#~ msgstr "échec du chargement de pywavefront :"

#~ msgid "invalid display dimensions"
#~ msgstr "dimensions d'affichage invalides"

#~ msgid "Did you add the pypilot_data repository?"
#~ msgstr "Avez-vous ajouté le dépôt pypilot_data ?"

#~ msgid "not found, texture compass cannot be used"
#~ msgstr "introuvable, la texture du compas ne peut pas être utilisée"

#~ msgid "Refresh"
#~ msgstr "Rafraîchir"

#~ msgid "Connected"
#~ msgstr "Connecté"

#~ msgid "Disconnected"
#~ msgstr "Déconnecté"

#~ msgid "warning, invalid choice value specified"
#~ msgstr "avertissement, valeur invalide spécifiée"

#~ msgid "pypilot Scope"
#~ msgstr "Scope pypilot"

#~ msgid "Zero"
#~ msgstr "Zéro"

#~ msgid "Scale +"
#~ msgstr "Echelle +"

#~ msgid "Scale -"
#~ msgstr "Echelle -"

#~ msgid "Offset /\\"
#~ msgstr "Décalage /\\"

#~ msgid "Offset \\/"
#~ msgstr "Décalage \\/"

#~ msgid "Freeze"
#~ msgstr "Geler"

#~ msgid "fftw"
#~ msgstr "fftw"

#~ msgid "Time"
#~ msgstr "Temps"

#~ msgid "values not found:"
#~ msgstr "valeurs non trouvées :"

#~ msgid "in"
#~ msgstr "dans"

#~ msgid "seconds"
#~ msgstr "secondes"

#~ msgid "nmea client failed to connect to"
#~ msgstr "Le client nmea a échoué à se connecter"

#~ msgid "failed to create nmea socket as host:port"
#~ msgstr "échec de la création de la socket nmea en tant qu'hôte:port"

#~ msgid "terminate calibration process"
#~ msgstr "terminer le processus d'étalonnage"
