# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-04-06 17:25-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: ../rudder.py:118
msgid "bad rudder calibration"
msgstr "slechte roerkalibratie"

#: ../rudder.py:122
msgid "bad servo rudder calibration"
msgstr "slechte kalibratie van het servoroer"

#: ../rudder.py:193
msgid "servo rudder autogain failed"
msgstr "servo roer autogain mislukt"

#: ../failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot kan de vereiste modules niet importeren. Ben je vergeten sudo "
"python3 setup.py install uit te voeren?"

#: ../pyjson.py:14
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"WAARSCHUWING: python ujson-bibliotheek is mislukt, parsing verbruikt meer "
"cpu c"

#: ../servo.py:453
msgid "servo calibration invalid"
msgstr "servo kalibratie ongeldig"

#: ../servo.py:588
msgid "failed to open servo on:"
msgstr "kon servo niet openen op:"

#: ../servo.py:595
msgid "failed set nonblocking/exclusive"
msgstr "mislukte set niet-blokkerend/exclusief"

#: ../servo.py:626 ../signalk.py:189
msgid "found"
msgstr "gevonden"

#: ../servo.py:743
msgid "loading servo calibration"
msgstr "servo-kalibratie laden"

#: ../servo.py:747
msgid "WARNING: using default servo calibration!!"
msgstr "WAARSCHUWING: gebruik standaard servokalibratie!!"

#: ../servo.py:756
msgid "probing"
msgstr "indringend"

#: ../servo.py:772
msgid "arduino servo detected"
msgstr "arduino servo gedetecteerd"

#: ../servo.py:781
msgid "device needed for option"
msgstr "apparaat nodig voor optie:"

#: ../nmea.py:109
msgid "nmea failed to parse gps"
msgstr "nmea kon gps niet ontleden"

#: ../nmea.py:149
msgid "nmea failed to parse wind"
msgstr "nmea kon wind niet ontleden"

#: ../nmea.py:211
msgid "exception parsing apb"
msgstr "uitzondering ontleden apb"

#: ../nmea.py:253 ../nmea.py:263
msgid "exception parsing vhw"
msgstr "uitzondering parseren vhw"

#: ../nmea.py:352
msgid "unhandled nmea pipe string"
msgstr "onverwerkte nmea pijp string"

#: ../nmea.py:405
msgid "lost serial"
msgstr "verloren serie"

#: ../nmea.py:428
msgid "nmea got flag for process pipe:"
msgstr "nmea kreeg vlag voor procespijp:"

#: ../nmea.py:450
msgid "is another process accessing it?"
msgstr "heeft een ander proces er toegang toe?"

#: ../nmea.py:452
msgid "serial device timed out"
msgstr "seriÃ«le apparaat time-out device"

#: ../nmea.py:521
msgid "failed to open"
msgstr "niet geslaagd te openen"

#: ../nmea.py:587
msgid "nmea server on port"
msgstr "nmea-server op poort"

#: ../nmea.py:587
msgid "bind failed."
msgstr "binden mislukt."

#: ../nmea.py:589
msgid "listening on port"
msgstr "luisteren op poort"

#: ../nmea.py:589
msgid "for nmea connections"
msgstr "voor nmea-verbindingen"

#: ../nmea.py:660
msgid "nmea server has too many connections"
msgstr "nmea-server heeft te veel verbindingen"

#: ../nmea.py:686
msgid "nmea client lost connection"
msgstr "nmea-client verbinding verbroken"

#: ../nmea.py:691
msgid "nmea sock not in sockets!"
msgstr "nmea sok niet in stopcontacten!"

#: ../nmea.py:702
msgid "nmea failed to unregister socket"
msgstr "nmea kan socket niet uitschrijven"

#: ../nmea.py:707
msgid "nmea failed to remove fd"
msgstr "nmea kan fd . niet verwijderen"

#: ../nmea.py:712
msgid "nmea failed to remove address"
msgstr "nmea kan adres niet verwijderen"

#: ../nmea.py:737
msgid "invalid value"
msgstr "ongeldige waarde"

#: ../nmea.py:747
msgid "connect error"
msgstr "verbindingsfout"

#: ../nmea.py:776 ../signalk.py:269
msgid "failed to connect"
msgstr "kon niet verbinden"

#: ../nmea.py:784
msgid "nmea client connected"
msgstr "nmea-client verbonden"

#: ../nmea.py:813
msgid "poll took too long in nmea process!"
msgstr "poll duurde te lang in nmea-proces!"

#: ../nmea.py:820
msgid "nmea bridge lost server connection"
msgstr "nmea bridge verbroken serververbinding"

#: ../nmea.py:823
msgid "nmea bridge lost pipe to autopilot"
msgstr "nmea bridge lost pipe naar stuurautomaat"

#: ../nmea.py:847
msgid "nmea bridge unhandled poll flag"
msgstr "nmea bridge onverwerkte poll vlag poll"

#: ../nmea.py:907
msgid "nmea process loop too slow:"
msgstr "nmea proceslus te langzaam:"

#: ../nonblockingpipe.py:40
msgid "error pipe block on recv!"
msgstr "fout pijpblok op recv!"

#: ../nonblockingpipe.py:42
msgid "failed to recv nonblocking pipe!"
msgstr "kon niet-blokkerende pijp herstellen!"

#: ../nonblockingpipe.py:69
msgid "pipe full"
msgstr "pijp vol"

#: ../nonblockingpipe.py:69
msgid "cannot send"
msgstr "Kan niet verzenden"

#: ../nonblockingpipe.py:89 ../nonblockingpipe.py:145
msgid "failed to decode data socket!"
msgstr "kan datasocket niet decoderen!"

#: ../nonblockingpipe.py:103
msgid "failed to encode data socket!"
msgstr "kan datasocket niet coderen!"

#: ../nonblockingpipe.py:155
msgid "failed write"
msgstr "mislukt schrijven"

#: ../server.py:106
msgid "ERROR no connections in watch"
msgstr "FOUT geen verbindingen in horloge"

#: ../server.py:209
msgid "remove duplicate udp connection"
msgstr "dubbele ud-verbinding verwijderen"

#: ../server.py:486
msgid "failed to monitor "
msgstr "niet kunnen monitoren"

#: ../server.py:490
msgid "creating config directory: "
msgstr "configuratiemap maken:"

#: ../server.py:497
msgid "failed to load"
msgstr "Laden mislukt"

#: ../server.py:508
msgid "backup data failed as well"
msgstr "back-upgegevens ook mislukt"

#: ../server.py:570
msgid "failed to write"
msgstr "kon niet schrijven"

#: ../server.py:625
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server: binding mislukt; draait er al een server?"

#: ../server.py:688
msgid "persistent store took too long!"
msgstr "aanhoudende winkel duurde te lang!"

#: ../server.py:706
msgid "max connections reached"
msgstr "max verbindingen bereikt"

#: ../server.py:709
msgid "server add socket"
msgstr "server socket toevoegen"

#: ../server.py:719
msgid "internal pipe closed, server exiting"
msgstr "interne pijp gesloten, server wordt afgesloten"

#: ../server.py:771
msgid "server socket closed from flush!!"
msgstr "server socket gesloten van flush!!"

#: ../signalk.py:52
msgid "service removed"
msgstr "dienst verwijderd"

#: ../signalk.py:55
msgid "server lost"
msgstr "server verloren"

#: ../signalk.py:61
msgid "service add"
msgstr "service toevoegen"

#: ../signalk.py:86 ../client.py:210
msgid "failed to"
msgstr "slaagde er niet in"

#: ../signalk.py:86
msgid "autodetection not possible"
msgstr "automatische detectie niet mogelijk"

#: ../signalk.py:87 ../signalk.py:176 ../signalk.py:246 ../client.py:211
msgid "try"
msgstr "proberen"

#: ../signalk.py:87 ../signalk.py:176 ../signalk.py:246 ../client.py:211
msgid "or"
msgstr "of"

#: ../signalk.py:138
msgid "read token"
msgstr "lees token"

#: ../signalk.py:141
msgid "failed to read token"
msgstr "token niet gelezen"

#: ../signalk.py:171
msgid "probe"
msgstr "sonde"

#: ../signalk.py:175
msgid "could not"
msgstr "kon niet"

#: ../signalk.py:185
msgid "failed to retrieve/parse data from"
msgstr "kan gegevens niet ophalen/parseren van"

#: ../signalk.py:201
msgid "see if token is ready"
msgstr "kijk of token klaar is"

#: ../signalk.py:207
msgid "received token"
msgstr "ontvangen token"

#: ../signalk.py:213
msgid "failed to store token"
msgstr "kan token niet opslaan"

#: ../signalk.py:217 ../signalk.py:238
msgid "error requesting access"
msgstr "fout bij het aanvragen van toegang"

#: ../signalk.py:236
msgid "request access url"
msgstr "toegangs-url aanvragen"

#: ../signalk.py:245
msgid "cannot create connection:"
msgstr "kan geen verbinding maken:"

#: ../signalk.py:260
msgid "bad status, rejecting token"
msgstr "slechte status, token afwijzen"

#: ../signalk.py:264
msgid "connection refused"
msgstr "Verbinding geweigerd"

#: ../signalk.py:313
msgid "server found"
msgstr "server gevonden"

#: ../signalk.py:334
msgid "connected to"
msgstr "verbonden met"

#: ../signalk.py:416
msgid "Exception converting signalk->pypilot"
msgstr "Uitzondering converteren signalk->pypilot"

#: ../signalk.py:430
msgid "received"
msgstr "ontvangen"

#: ../signalk.py:493
msgid "failed to send updates"
msgstr "kan geen updates verzenden"

#: ../signalk.py:507
msgid "failed to parse msg:"
msgstr "kon bericht niet ontleden:"

#: ../sensors.py:49
msgid "sensor found"
msgstr "sensor gevonden"

#: ../sensors.py:413
msgid "unknown data parsed!"
msgstr "onbekende gegevens geparseerd!"

#: ../calibration_fit.py:38
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"kan wetenschappelijke bibliotheek niet laden, kan kalibratie-update niet "
"uitvoeren!"

#: ../calibration_fit.py:701
msgid "Bad Accelerometer Calibration"
msgstr "Slechte versnellingsmeterkalibratie"

#: ../calibration_fit.py:735
msgid "magnetic distortions"
msgstr "magnetische vervormingen"

#: ../pilots/__init__.py:22
msgid "ERROR loading"
msgstr "Fout bij het laden"

#: ../autopilot.py:135
msgid "failed to load pilot"
msgstr "kan piloot niet laden"

#: ../autopilot.py:138
msgid "Available Pilots"
msgstr "Beschikbare piloten"

#: ../autopilot.py:157
msgid "warning: failed to open special file"
msgstr "waarschuwing: kan speciaal bestand niet openen"

#: ../autopilot.py:157
msgid "for writing"
msgstr "om te schrijven"

#: ../autopilot.py:158
msgid "cannot stroke the watchdog"
msgstr "kan de waakhond niet aaien"

#: ../autopilot.py:162
msgid "warning: failed to make autopilot process realtime"
msgstr "waarschuwing: kon stuurautomaatproces niet realtime maken"

#: ../autopilot.py:347
msgid "server/client is running too _slowly_"
msgstr "server/client draait te _langzaam_"

#: ../autopilot.py:353
msgid "sensors is running too _slowly_"
msgstr "sensoren lopen te langzaam"

#: ../autopilot.py:453
msgid "autopilot routine is running too _slowly_"
msgstr "automatische piloot-routine loopt te langzaam"

#: ../autopilot.py:465
msgid "servo is running too _slowly_"
msgstr "servo loopt te langzaam"

#: ../autopilot.py:475
msgid "autopilot iteration running too slow"
msgstr "iteratie van de stuurautomaat loopt te langzaam"

#: ../autopilot.py:488
msgid "WARNING: running autopilot as root!!"
msgstr "WAARSCHUWING: autopilot draaien als root!!"

#: ../autopilot.py:490
msgid "init complete"
msgstr "begin voltooid"

#: ../boatimu.py:33
msgid "RTIMU library not detected, please install it"
msgstr "RTIMU-bibliotheek niet gedetecteerd, installeer deze a.u.b."

#: ../boatimu.py:57
msgid "Using settings file"
msgstr "Instellingenbestand gebruiken"

#: ../boatimu.py:97
msgid "ERROR: No IMU Detected"
msgstr "FOUT: geen IMU gedetecteerd"

#: ../boatimu.py:105
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr "FOUT: IMU-initiatie mislukt, geen traagheidsgegevens beschikbaar"

#: ../boatimu.py:131
msgid "warning, failed to make imu process realtime"
msgstr "waarschuwing, kon imu-proces niet realtime maken"

#: ../boatimu.py:133
msgid "made imu process realtime"
msgstr "gemaakt imu proces realtime"

#: ../boatimu.py:145
msgid "setting initial gyro bias"
msgstr "initiÃ«le gyro-bias instellen"

#: ../boatimu.py:161
msgid "imu process failed to keep time"
msgstr "imu-proces kon de tijd niet bijhouden"

#: ../boatimu.py:169
msgid "failed to read IMU!"
msgstr "kan IMU niet lezen!"

#: ../boatimu.py:202
msgid "imu rate set to rate"
msgstr "imu tarief ingesteld op tarief"

#: ../boatimu.py:230
msgid "too high standing gyro bias, resetting sensors"
msgstr "te hoge staande gyro-bias, sensoren resetten"

#: ../boatimu.py:235
msgid "compass out of range, resetting"
msgstr "kompas buiten bereik, resetten"

#: ../boatimu.py:327
msgid "warning, failed to make calibration process other"
msgstr "waarschuwing, kan het kalibratieproces niet anders maken"

#: ../boatimu.py:329
msgid "warning, failed to make calibration process idle, trying renice"
msgstr ""
"waarschuwing, kan het kalibratieproces niet inactief maken, probeer renice"

#: ../boatimu.py:331
msgid "warning, failed to renice calibration process"
msgstr "waarschuwing, kan het kalibratieproces niet herroepen"

#: ../boatimu.py:338
msgid "calibration loaded, starting"
msgstr "kalibratie geladen, starten"

#: ../boatimu.py:342
msgid "failed import calibration fit"
msgstr "mislukte import kalibratie fit"

#: ../boatimu.py:460
msgid "accel values invalid"
msgstr "accel waarden ongeldig"

#: ../bufferedsocket.py:55
msgid "overflow in pypilot udp socket"
msgstr "overloop in pypilot udp-socket"

#: ../bufferedsocket.py:60
msgid "overflow in pypilot socket"
msgstr "overloop in pypilot-socket"

#: ../bufferedsocket.py:75
msgid "failed to send udp packet"
msgstr "kan ud-pakket niet verzenden"

#: ../bufferedsocket.py:84
msgid "pypilot socket failed to send to"
msgstr "pypilot-socket kan niet worden verzonden naar"

#: ../bufferedsocket.py:98
msgid "socket send took too long!?!?"
msgstr "socket verzenden duurde te lang!?!?"

#: ../bufferedsocket.py:100
msgid "socket send error"
msgstr "socket verzend fout"

#: ../bufferedsocket.py:104
msgid "pypilot socket exception"
msgstr "pypilot socket-uitzondering"

#: ../bufferedsocket.py:108
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr "terugvallen op python nonblocking socket, zal meer cpu verbruiken"

#: ../bufferedsocket.py:134
msgid "socket send error in server flush"
msgstr "socket verzend fout in server flush"

#: ../bufferedsocket.py:149
msgid "error receiving data"
msgstr "fout bij het ontvangen van gegevens"

#: ../serialprobe.py:30
msgid "error reading"
msgstr "fout bij het lezen"

#: ../serialprobe.py:86
msgid "found more devices by path"
msgstr "meer apparaten gevonden op pad"

#: ../serialprobe.py:118
msgid "removing gps device"
msgstr "gps-apparaat verwijderen"

#: ../serialprobe.py:197
msgid "no pyudev module! will scan usb devices often!"
msgstr "geen pyudev-module! scant vaak usb-apparaten!"

#: ../serialprobe.py:359
msgid "success"
msgstr "succes"

#: ../serialprobe.py:367
msgid "failed to record device"
msgstr "kan apparaat niet opnemen"

#: ../client.py:93
msgid "warning, registering existing value:"
msgstr "waarschuwing, bestaande waarde registreren:"

#: ../client.py:154
msgid "failed to read config file:"
msgstr "kon configuratiebestand niet lezen:"

#: ../client.py:188
msgid "failed to write config file:"
msgstr "kon configuratiebestand niet schrijven:"

#: ../client.py:190
msgid "Exception writing config file:"
msgstr "Uitzondering schrijven configuratiebestand:"

#: ../client.py:210
msgid "autodetecting pypilot server not possible"
msgstr "automatische detectie van pypilot-server niet mogelijk"

#: ../client.py:319
msgid "invalid message from server:"
msgstr "ongeldig bericht van server:"

#: ../client.py:343
msgid "warning, pypilot client aleady has connection"
msgstr "waarschuwing, pypilot-client heeft al verbinding"

#: ../client.py:363
msgid "connect failed to"
msgstr "verbinding mislukt"

#: ../client.py:460 ../client.py:463
msgid "failed to connect to"
msgstr "kan geen verbinding maken met"

#: ../client.py:466
msgid "no pypilot server found"
msgstr "geen pypilot-server gevonden"

#: ../client.py:522
msgid "usage"
msgstr "gebruik"

#: ../client.py:525
msgid "set the host or ip address"
msgstr "stel het host- of ip-adres in"

#: ../client.py:526
msgid "print info about each value type"
msgstr "info afdrukken over elk waardetype"

#: ../client.py:527
msgid "continuous watch"
msgstr "continu kijken"

#: ../client.py:528
msgid "show this message"
msgstr "toon dit bericht"

#: ../client.py:555
msgid "failed to retrieve value list!"
msgstr "kan de waardelijst niet ophalen!"

#: ../client.py:566
msgid "timeout retrieving"
msgstr "time-out ophalen"

#: ../client.py:569
msgid "missing"
msgstr "missend"

#: ../values.py:135
msgid "invalid initial value for range property"
msgstr "ongeldige beginwaarde voor bereikeigenschap"

#: ../values.py:184
msgid "invalid set"
msgstr "ongeldige set"

#: ../gpsd.py:46
msgid "gpsd connected"
msgstr "gpsd aangesloten"

#: ../gpsd.py:50
msgid "gpsd failed to connect"
msgstr "gpsd kan geen verbinding maken"

#: ../gpsd.py:56
msgid "exception connecting to gps"
msgstr "uitzondering verbinden met gps"

#: ../gpsd.py:60
msgid "gpsd disconnected"
msgstr "gpsd losgekoppeld"

#: ../gpsd.py:74
msgid "gpsd PROBE success"
msgstr "gpsd PROBE succes"

#: ../gpsd.py:82
msgid "gpsd probe failed"
msgstr "gpsd-sonde mislukt"

#: ../gpsd.py:105
msgid "gpsd deactivated"
msgstr "gpsd gedeactiveerd"

#: ../gpsd.py:147
msgid "gpsd failed to determine serial baud rate of device"
msgstr "gpsd kon de seriÃ«le baudsnelheid van het apparaat niet bepalen"

#: ../gpsd.py:164
msgid "gpsd timeout from lack of data"
msgstr "gpsd time-out door gebrek aan gegevens"

#: ../gpsd.py:179
msgid "gpsd received invalid message"
msgstr "gpsd heeft ongeldig bericht ontvangen"

#: ../gpsd.py:224
msgid "gpsd got flag for pipe:"
msgstr "gpsd kreeg vlag voor pijp:"

#: ../gpsd.py:233
msgid "gpsd serial probe"
msgstr "gpsd seriÃ«le sonde"

#~ msgid "exception in calibration:"
#~ msgstr "uitzondering in kalibratie:"

#~ msgid "warning: unhandled message"
#~ msgstr "waarschuwing: onverwerkt bericht"

#~ msgid "Autopilot Control"
#~ msgstr "Stuurautomaatbediening"

#~ msgid "AP"
#~ msgstr "U"

#~ msgid "N/A"
#~ msgstr "Nvt"

#~ msgid "        N/A        "
#~ msgstr "Nvt"

#~ msgid "----"
#~ msgstr "----"

#~ msgid " N/A "
#~ msgstr "Nvt"

#~ msgid "port"
#~ msgstr "haven"

#~ msgid "starboard"
#~ msgstr "stuurboord"

#~ msgid "Pilot"
#~ msgstr "piloot"

#~ msgid "Compass"
#~ msgstr "Kompas"

#~ msgid "GPS"
#~ msgstr "GPS"

#~ msgid "Wind"
#~ msgstr "Wind"

#~ msgid "True Wind"
#~ msgstr "Ware wind"

#~ msgid "Center"
#~ msgstr "Centrum"

#~ msgid "&Scope"
#~ msgstr "&Reikwijdte"

#~ msgid "&Client"
#~ msgstr "&CliÃ«nt"

#~ msgid "C&alibration"
#~ msgstr "K&alibratie"

#~ msgid "Close"
#~ msgstr "Dichtbij"

#~ msgid "Calibration"
#~ msgstr "Kalibratie"

#~ msgid "Boat is level"
#~ msgstr "Boot ligt waterpas"

#~ msgid "Reset"
#~ msgstr "Resetten"

#~ msgid "Alignment"
#~ msgstr "Uitlijning"

#~ msgid "Heading"
#~ msgstr "rubriek"

#~ msgid "     N/A     "
#~ msgstr "Nvt"

#~ msgid "Offset"
#~ msgstr "offset"

#~ msgid "Coords"
#~ msgstr "CoÃ¶rdinaten"

#~ msgid "Sea"
#~ msgstr "Zee"

#~ msgid "Boat"
#~ msgstr "Boot"

#~ msgid "Scope"
#~ msgstr "Toepassingsgebied"

#~ msgid "Pitch"
#~ msgstr "Standplaats"

#~ msgid "Roll"
#~ msgstr "Rollen"

#~ msgid "Heel"
#~ msgstr "Hiel"

#~ msgid "alignment"
#~ msgstr "uitlijning"

#~ msgid "Calibration Age"
#~ msgstr "Kalibratieleeftijd:"

#~ msgid "Clear"
#~ msgstr "Doorzichtig"

#~ msgid "calibration locked"
#~ msgstr "kalibratie vergrendeld"

#~ msgid "accel"
#~ msgstr "accel"

#~ msgid "Sigma Points"
#~ msgstr "Sigma-punten"

#~ msgid "local history"
#~ msgstr "lokale geschiedenis"

#~ msgid "current"
#~ msgstr "actueel"

#~ msgid "Calibration Points"
#~ msgstr "Kalibratiepunten"

#~ msgid "compass"
#~ msgstr "kompas"

#~ msgid ""
#~ "Press each button when the rudder is at the correct position to calibrate."
#~ msgstr ""
#~ "Druk op elke knop wanneer het roer in de juiste positie staat om te "
#~ "kalibreren."

#~ msgid "Rudder"
#~ msgstr "Roer"

#~ msgid "Reset Calibration"
#~ msgstr "Kalibratie resetten"

#~ msgid "Rudder Is Centered"
#~ msgstr "Roer is gecentreerd"

#~ msgid "------"
#~ msgstr "------"

#~ msgid "Rudder is Starboard Range"
#~ msgstr "Roer is stuurboord bereik"

#~ msgid "Scale"
#~ msgstr "Schaal"

#~ msgid "Rudder is Port Range"
#~ msgstr "Roer is bakboordbereik"

#~ msgid "Non Linearity"
#~ msgstr "Niet-lineariteit"

#~ msgid " range +-"
#~ msgstr "bereik +-"

#~ msgid "degrees"
#~ msgstr "graden"

#~ msgid "rudder"
#~ msgstr "roer"

#~ msgid "settings"
#~ msgstr "instellingen"

#~ msgid "failed to load pywavefront:"
#~ msgstr "kan pywavefront niet laden:"

#~ msgid "invalid display dimensions"
#~ msgstr "ongeldige schermafmetingen"

#~ msgid "Did you add the pypilot_data repository?"
#~ msgstr "Heb je de pypilot_data-repository toegevoegd?"

#~ msgid "not found, texture compass cannot be used"
#~ msgstr "niet gevonden, textuurkompas kan niet worden gebruikt"

#~ msgid "Refresh"
#~ msgstr "Vernieuwen"

#~ msgid "Connected"
#~ msgstr "Verbonden"

#~ msgid "Disconnected"
#~ msgstr "Verbinding verbroken"

#~ msgid "warning, invalid choice value specified"
#~ msgstr "waarschuwing, ongeldige keuzewaarde opgegeven"

#~ msgid "pypilot Scope"
#~ msgstr "pypilot-bereik"

#~ msgid "Zero"
#~ msgstr "Nul"

#~ msgid "Scale +"
#~ msgstr "Schaal +"

#~ msgid "Scale -"
#~ msgstr "Schaal -"

#~ msgid "Offset /\\"
#~ msgstr "verschuiving /\\"

#~ msgid "Offset \\/"
#~ msgstr "Verschuiving /"

#~ msgid "Freeze"
#~ msgstr "Bevriezen"

#~ msgid "fftw"
#~ msgstr "fftw"

#~ msgid "Time"
#~ msgstr "Tijd"

#~ msgid "values not found:"
#~ msgstr "waarden niet gevonden:"

#~ msgid "in"
#~ msgstr "in"

#~ msgid "seconds"
#~ msgstr "seconden"

#~ msgid "nmea client failed to connect to"
#~ msgstr "nmea-client kan geen verbinding maken met"

#~ msgid "failed to create nmea socket as host:port"
#~ msgstr "kan nmea socket niet maken als host:poort"

#~ msgid "terminate calibration process"
#~ msgstr "kalibratieproces beÃ«indigen"
