# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-04-06 17:25-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: ../rudder.py:118
msgid "bad rudder calibration"
msgstr "dårlig rorkalibrering"

#: ../rudder.py:122
msgid "bad servo rudder calibration"
msgstr "dårlig servoror kalibrering"

#: ../rudder.py:193
msgid "servo rudder autogain failed"
msgstr "servoror autogain mislyktes"

#: ../failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot kunne ikke importere nødvendige moduler. Glemte du å kjøre sudo "
"python3 setup.py install?"

#: ../pyjson.py:14
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"ADVARSEL: Python ujson-biblioteket mislyktes, parsing vil forbruke mer CPU"

#: ../servo.py:453
msgid "servo calibration invalid"
msgstr "servokalibrering ugyldig"

#: ../servo.py:588
msgid "failed to open servo on:"
msgstr "mislyktes i å åpne servo på:"

#: ../servo.py:595
msgid "failed set nonblocking/exclusive"
msgstr "mislykket sett ikke-blokkering / eksklusivt"

#: ../servo.py:626 ../signalk.py:189
msgid "found"
msgstr "funnet"

#: ../servo.py:743
msgid "loading servo calibration"
msgstr "lasting av servokalibrering"

#: ../servo.py:747
msgid "WARNING: using default servo calibration!!"
msgstr "ADVARSEL: bruker standard servokalibrering !!"

#: ../servo.py:756
msgid "probing"
msgstr "sondering"

#: ../servo.py:772
msgid "arduino servo detected"
msgstr "arduino servo oppdaget"

#: ../servo.py:781
msgid "device needed for option"
msgstr "enheten som trengs for alternativet"

#: ../nmea.py:109
msgid "nmea failed to parse gps"
msgstr "nmea kunne ikke analysere GPS"

#: ../nmea.py:149
msgid "nmea failed to parse wind"
msgstr "nmea klarte ikke å analysere vind"

#: ../nmea.py:211
msgid "exception parsing apb"
msgstr "unntak parsing apb"

#: ../nmea.py:253 ../nmea.py:263
msgid "exception parsing vhw"
msgstr "unntak parsing vhw"

#: ../nmea.py:352
msgid "unhandled nmea pipe string"
msgstr "uhåndtert nmea rørstreng"

#: ../nmea.py:405
msgid "lost serial"
msgstr "mistet serie"

#: ../nmea.py:428
msgid "nmea got flag for process pipe:"
msgstr "nmea fikk flagg for prosessrør:"

#: ../nmea.py:450
msgid "is another process accessing it?"
msgstr "får en annen prosess tilgang til den?"

#: ../nmea.py:452
msgid "serial device timed out"
msgstr "seriell enhet ble tidsavbrutt"

#: ../nmea.py:521
msgid "failed to open"
msgstr "kunne ikke åpnes"

#: ../nmea.py:587
msgid "nmea server on port"
msgstr "nmea server på port"

#: ../nmea.py:587
msgid "bind failed."
msgstr "bind mislyktes."

#: ../nmea.py:589
msgid "listening on port"
msgstr "lytter på port"

#: ../nmea.py:589
msgid "for nmea connections"
msgstr "for nmea-forbindelser"

#: ../nmea.py:660
msgid "nmea server has too many connections"
msgstr "nmea server har for mange tilkoblinger"

#: ../nmea.py:686
msgid "nmea client lost connection"
msgstr "nmea klient mistet tilkoblingen"

#: ../nmea.py:691
msgid "nmea sock not in sockets!"
msgstr "nmea sokk ikke i stikkontakter!"

#: ../nmea.py:702
msgid "nmea failed to unregister socket"
msgstr "nmea kunne ikke avregistrere kontakten"

#: ../nmea.py:707
msgid "nmea failed to remove fd"
msgstr "nmea klarte ikke å fjerne fd"

#: ../nmea.py:712
msgid "nmea failed to remove address"
msgstr "nmea kunne ikke fjerne adressen"

#: ../nmea.py:737
msgid "invalid value"
msgstr "ugyldig verdi"

#: ../nmea.py:747
msgid "connect error"
msgstr "tilkoblingsfeil"

#: ../nmea.py:776 ../signalk.py:269
msgid "failed to connect"
msgstr "tilkobling mislyktes"

#: ../nmea.py:784
msgid "nmea client connected"
msgstr "nmea klient tilkoblet"

#: ../nmea.py:813
msgid "poll took too long in nmea process!"
msgstr "avstemningen tok for lang tid i nmea-prosessen!"

#: ../nmea.py:820
msgid "nmea bridge lost server connection"
msgstr "nmea bridge mistet serverforbindelse"

#: ../nmea.py:823
msgid "nmea bridge lost pipe to autopilot"
msgstr "nmea bridge mistet rør til autopilot"

#: ../nmea.py:847
msgid "nmea bridge unhandled poll flag"
msgstr "nmea bridge uhåndtert avstemningsflagg"

#: ../nmea.py:907
msgid "nmea process loop too slow:"
msgstr "nmea prosessløkke for sakte:"

#: ../nonblockingpipe.py:40
msgid "error pipe block on recv!"
msgstr "feil rørblokk på recv!"

#: ../nonblockingpipe.py:42
msgid "failed to recv nonblocking pipe!"
msgstr "mislyktes i å rekvirere ikke-blokkerende rør!"

#: ../nonblockingpipe.py:69
msgid "pipe full"
msgstr "rør fullt"

#: ../nonblockingpipe.py:69
msgid "cannot send"
msgstr "kan ikke sende"

#: ../nonblockingpipe.py:89 ../nonblockingpipe.py:145
msgid "failed to decode data socket!"
msgstr "kunne ikke dekode datakontakten!"

#: ../nonblockingpipe.py:103
msgid "failed to encode data socket!"
msgstr "kunne ikke kode datakontakten!"

#: ../nonblockingpipe.py:155
msgid "failed write"
msgstr "mislyktes skrive"

#: ../server.py:106
msgid "ERROR no connections in watch"
msgstr "FEIL ingen tilkoblinger i klokken"

#: ../server.py:209
msgid "remove duplicate udp connection"
msgstr "Fjern duplikat UDP-tilkobling"

#: ../server.py:486
msgid "failed to monitor "
msgstr "klarte ikke å overvåke"

#: ../server.py:490
msgid "creating config directory: "
msgstr "oppretter konfigurasjonskatalog:"

#: ../server.py:497
msgid "failed to load"
msgstr "kunne ikke laste"

#: ../server.py:508
msgid "backup data failed as well"
msgstr "sikkerhetskopieringsdata mislyktes også"

#: ../server.py:570
msgid "failed to write"
msgstr "klarte ikke å skrive"

#: ../server.py:625
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server: bind mislyktes; kjører du allerede en server?"

#: ../server.py:688
msgid "persistent store took too long!"
msgstr "vedvarende butikk tok for lang tid!"

#: ../server.py:706
msgid "max connections reached"
msgstr "maks. forbindelser nådd"

#: ../server.py:709
msgid "server add socket"
msgstr "server legge til stikkontakt"

#: ../server.py:719
msgid "internal pipe closed, server exiting"
msgstr "internt rør lukket, serveren avsluttes"

#: ../server.py:771
msgid "server socket closed from flush!!"
msgstr "serveruttak stengt fra spyling !!"

#: ../signalk.py:52
msgid "service removed"
msgstr "tjenesten fjernet"

#: ../signalk.py:55
msgid "server lost"
msgstr "server tapt"

#: ../signalk.py:61
msgid "service add"
msgstr "tjenestetillegg"

#: ../signalk.py:86 ../client.py:210
msgid "failed to"
msgstr "feilet med å"

#: ../signalk.py:86
msgid "autodetection not possible"
msgstr "autodeteksjon ikke mulig"

#: ../signalk.py:87 ../signalk.py:176 ../signalk.py:246 ../client.py:211
msgid "try"
msgstr "prøve"

#: ../signalk.py:87 ../signalk.py:176 ../signalk.py:246 ../client.py:211
msgid "or"
msgstr "eller"

#: ../signalk.py:138
msgid "read token"
msgstr "les token"

#: ../signalk.py:141
msgid "failed to read token"
msgstr "mislyktes i å lese token"

#: ../signalk.py:171
msgid "probe"
msgstr "sonde"

#: ../signalk.py:175
msgid "could not"
msgstr "kunne ikke"

#: ../signalk.py:185
msgid "failed to retrieve/parse data from"
msgstr "mislyktes i å hente / analysere data fra"

#: ../signalk.py:201
msgid "see if token is ready"
msgstr "se om token er klar"

#: ../signalk.py:207
msgid "received token"
msgstr "mottatt token"

#: ../signalk.py:213
msgid "failed to store token"
msgstr "mislyktes i å lagre token"

#: ../signalk.py:217 ../signalk.py:238
msgid "error requesting access"
msgstr "feil med å be om tilgang"

#: ../signalk.py:236
msgid "request access url"
msgstr "be om tilgangsadresse"

#: ../signalk.py:245
msgid "cannot create connection:"
msgstr "kan ikke opprette forbindelse:"

#: ../signalk.py:260
msgid "bad status, rejecting token"
msgstr "dårlig status, avviser token"

#: ../signalk.py:264
msgid "connection refused"
msgstr "forbindelsen nektet"

#: ../signalk.py:313
msgid "server found"
msgstr "server funnet"

#: ../signalk.py:334
msgid "connected to"
msgstr "Koblet til"

#: ../signalk.py:416
msgid "Exception converting signalk->pypilot"
msgstr "Unntak konvertere signalk-> pypilot"

#: ../signalk.py:430
msgid "received"
msgstr "mottatt"

#: ../signalk.py:493
msgid "failed to send updates"
msgstr "kunne ikke sende oppdateringer"

#: ../signalk.py:507
msgid "failed to parse msg:"
msgstr "klarte ikke å analysere meldingen:"

#: ../sensors.py:49
msgid "sensor found"
msgstr "sensor funnet"

#: ../sensors.py:413
msgid "unknown data parsed!"
msgstr "ukjente data analysert!"

#: ../calibration_fit.py:38
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"kunne ikke laste vitenskapelig bibliotek, kan ikke utføre "
"kalibreringsoppdatering!"

#: ../calibration_fit.py:701
msgid "Bad Accelerometer Calibration"
msgstr "Dårlig akselerometerkalibrering"

#: ../calibration_fit.py:735
msgid "magnetic distortions"
msgstr "magnetiske forvrengninger"

#: ../pilots/__init__.py:22
msgid "ERROR loading"
msgstr "Feil ved innlasting"

#: ../autopilot.py:135
msgid "failed to load pilot"
msgstr "mislyktes i å laste pilot"

#: ../autopilot.py:138
msgid "Available Pilots"
msgstr "Tilgjengelige piloter"

#: ../autopilot.py:157
msgid "warning: failed to open special file"
msgstr "advarsel: kunne ikke åpne spesialfil"

#: ../autopilot.py:157
msgid "for writing"
msgstr "for skriving"

#: ../autopilot.py:158
msgid "cannot stroke the watchdog"
msgstr "kan ikke stryke vakthunden"

#: ../autopilot.py:162
msgid "warning: failed to make autopilot process realtime"
msgstr "advarsel: kunne ikke gjøre autopilotprosessen i sanntid"

#: ../autopilot.py:347
msgid "server/client is running too _slowly_"
msgstr "server / klient kjører også _slowly_"

#: ../autopilot.py:353
msgid "sensors is running too _slowly_"
msgstr "sensorene går for sakte"

#: ../autopilot.py:453
msgid "autopilot routine is running too _slowly_"
msgstr "autopilotrutinen går for sakte"

#: ../autopilot.py:465
msgid "servo is running too _slowly_"
msgstr "servo går for sakte"

#: ../autopilot.py:475
msgid "autopilot iteration running too slow"
msgstr "autopilot iterasjon kjører for sakte"

#: ../autopilot.py:488
msgid "WARNING: running autopilot as root!!"
msgstr "ADVARSEL: kjører autopilot som root!!"

#: ../autopilot.py:490
msgid "init complete"
msgstr "init fullført"

#: ../boatimu.py:33
msgid "RTIMU library not detected, please install it"
msgstr "RTIMU-biblioteket ble ikke oppdaget. Installer det"

#: ../boatimu.py:57
msgid "Using settings file"
msgstr "Bruker innstillingsfil"

#: ../boatimu.py:97
msgid "ERROR: No IMU Detected"
msgstr "FEIL: Ingen IMU oppdaget"

#: ../boatimu.py:105
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr "FEIL: IMU Init mislyktes, ingen treghetsdata tilgjengelig"

#: ../boatimu.py:131
msgid "warning, failed to make imu process realtime"
msgstr "advarsel, klarte ikke å gjøre imu-prosessen i sanntid"

#: ../boatimu.py:133
msgid "made imu process realtime"
msgstr "laget imu-prosessen i sanntid"

#: ../boatimu.py:145
msgid "setting initial gyro bias"
msgstr "sette innledende gyro bias"

#: ../boatimu.py:161
msgid "imu process failed to keep time"
msgstr "imu-prosessen klarte ikke å holde tiden"

#: ../boatimu.py:169
msgid "failed to read IMU!"
msgstr "mislyktes i å lese IMU!"

#: ../boatimu.py:202
msgid "imu rate set to rate"
msgstr "imu rate satt til rate"

#: ../boatimu.py:230
msgid "too high standing gyro bias, resetting sensors"
msgstr "for høy stående gyroforstyrrelse, tilbakestiller sensorer"

#: ../boatimu.py:235
msgid "compass out of range, resetting"
msgstr "kompass utenfor rekkevidde, tilbakestilles"

#: ../boatimu.py:327
msgid "warning, failed to make calibration process other"
msgstr "advarsel, klarte ikke å gjøre kalibreringsprosessen annen"

#: ../boatimu.py:329
msgid "warning, failed to make calibration process idle, trying renice"
msgstr ""
"advarsel, klarte ikke å gjøre kalibreringsprosessen inaktiv, og prøvde å "
"nekte"

#: ../boatimu.py:331
msgid "warning, failed to renice calibration process"
msgstr "advarsel, mislyktes i å nekte kalibreringsprosessen"

#: ../boatimu.py:338
msgid "calibration loaded, starting"
msgstr "kalibrering lastet, starter"

#: ../boatimu.py:342
msgid "failed import calibration fit"
msgstr "mislykket importkalibreringstilpasning"

#: ../boatimu.py:460
msgid "accel values invalid"
msgstr "accel-verdiene er ugyldige"

#: ../bufferedsocket.py:55
msgid "overflow in pypilot udp socket"
msgstr "overløp i pypilot udp-stikkontakt"

#: ../bufferedsocket.py:60
msgid "overflow in pypilot socket"
msgstr "overløp i pypilotkontakt"

#: ../bufferedsocket.py:75
msgid "failed to send udp packet"
msgstr "kunne ikke sende udp-pakken"

#: ../bufferedsocket.py:84
msgid "pypilot socket failed to send to"
msgstr "pypilot-kontakten kunne ikke sendes til"

#: ../bufferedsocket.py:98
msgid "socket send took too long!?!?"
msgstr "socket send tok for lang tid!?!?"

#: ../bufferedsocket.py:100
msgid "socket send error"
msgstr "stikkontaktfeil"

#: ../bufferedsocket.py:104
msgid "pypilot socket exception"
msgstr "unntak for pypilotuttak"

#: ../bufferedsocket.py:108
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr ""
"faller tilbake til python ikke-blokkerende stikkontakt, vil forbruke mer CPU"

#: ../bufferedsocket.py:134
msgid "socket send error in server flush"
msgstr "socket sende feil i serveren flush"

#: ../bufferedsocket.py:149
msgid "error receiving data"
msgstr "feil ved mottak av data"

#: ../serialprobe.py:30
msgid "error reading"
msgstr "feillesing"

#: ../serialprobe.py:86
msgid "found more devices by path"
msgstr "fant flere enheter etter sti"

#: ../serialprobe.py:118
msgid "removing gps device"
msgstr "fjerne GPS-enhet"

#: ../serialprobe.py:197
msgid "no pyudev module! will scan usb devices often!"
msgstr "ingen pyudev-modul! vil skanne USB-enheter ofte!"

#: ../serialprobe.py:359
msgid "success"
msgstr "suksess"

#: ../serialprobe.py:367
msgid "failed to record device"
msgstr "kunne ikke registrere enheten"

#: ../client.py:93
msgid "warning, registering existing value:"
msgstr "advarsel, registrere eksisterende verdi:"

#: ../client.py:154
msgid "failed to read config file:"
msgstr "mislyktes i å lese konfigurasjonsfilen:"

#: ../client.py:188
msgid "failed to write config file:"
msgstr "mislyktes i å skrive konfigurasjonsfil:"

#: ../client.py:190
msgid "Exception writing config file:"
msgstr "Unntak for å skrive konfigurasjonsfil:"

#: ../client.py:210
msgid "autodetecting pypilot server not possible"
msgstr "autodetecting pypilot server ikke mulig"

#: ../client.py:319
msgid "invalid message from server:"
msgstr "ugyldig melding fra server:"

#: ../client.py:343
msgid "warning, pypilot client aleady has connection"
msgstr "advarsel, har pypilot-klienten allerede tilkobling"

#: ../client.py:363
msgid "connect failed to"
msgstr "koble mislyktes i"

#: ../client.py:460 ../client.py:463
msgid "failed to connect to"
msgstr "kunne ikke koble til"

#: ../client.py:466
msgid "no pypilot server found"
msgstr "ingen pypilotserver funnet"

#: ../client.py:522
msgid "usage"
msgstr "bruk"

#: ../client.py:525
msgid "set the host or ip address"
msgstr "angi verten eller ip-adressen"

#: ../client.py:526
msgid "print info about each value type"
msgstr "skrive ut info om hver verditype"

#: ../client.py:527
msgid "continuous watch"
msgstr "kontinuerlig klokke"

#: ../client.py:528
msgid "show this message"
msgstr "vis denne meldingen"

#: ../client.py:555
msgid "failed to retrieve value list!"
msgstr "mislyktes i å hente verdilisten!"

#: ../client.py:566
msgid "timeout retrieving"
msgstr "timeout henting"

#: ../client.py:569
msgid "missing"
msgstr "savnet"

#: ../values.py:135
msgid "invalid initial value for range property"
msgstr "ugyldig opprinnelig verdi for områdeegenskap"

#: ../values.py:184
msgid "invalid set"
msgstr "ugyldig sett"

#: ../gpsd.py:46
msgid "gpsd connected"
msgstr "GPSD tilkoblet"

#: ../gpsd.py:50
msgid "gpsd failed to connect"
msgstr "gpsd kunne ikke koble til"

#: ../gpsd.py:56
msgid "exception connecting to gps"
msgstr "unntak som kobler til GPS"

#: ../gpsd.py:60
msgid "gpsd disconnected"
msgstr "gpsd frakoblet"

#: ../gpsd.py:74
msgid "gpsd PROBE success"
msgstr "gpsd PROBE suksess"

#: ../gpsd.py:82
msgid "gpsd probe failed"
msgstr "gpsd-sonde mislyktes"

#: ../gpsd.py:105
msgid "gpsd deactivated"
msgstr "GPSD deaktivert"

#: ../gpsd.py:147
msgid "gpsd failed to determine serial baud rate of device"
msgstr "gpsd kunne ikke bestemme seriell overføringshastighet for enheten"

#: ../gpsd.py:164
msgid "gpsd timeout from lack of data"
msgstr "gpsd timeout fra mangel på data"

#: ../gpsd.py:179
msgid "gpsd received invalid message"
msgstr "gpsd mottok ugyldig melding"

#: ../gpsd.py:224
msgid "gpsd got flag for pipe:"
msgstr "gpsd fikk flagg for pipe:"

#: ../gpsd.py:233
msgid "gpsd serial probe"
msgstr "gpsd seriell sonde"

#~ msgid "exception in calibration:"
#~ msgstr "unntak i kalibrering:"

#~ msgid "warning: unhandled message"
#~ msgstr "advarsel: ubehandlet melding"

#~ msgid "Autopilot Control"
#~ msgstr "Autopilotkontroll"

#~ msgid "AP"
#~ msgstr "Du"

#~ msgid "N/A"
#~ msgstr "Ikke relevant"

#~ msgid "        N/A        "
#~ msgstr "Ikke relevant"

#~ msgid "----"
#~ msgstr "----"

#~ msgid " N/A "
#~ msgstr "Ikke relevant"

#~ msgid "port"
#~ msgstr "havn"

#~ msgid "starboard"
#~ msgstr "styrbord"

#~ msgid "Pilot"
#~ msgstr "Pilot"

#~ msgid "Compass"
#~ msgstr "Kompass"

#~ msgid "GPS"
#~ msgstr "GPS"

#~ msgid "Wind"
#~ msgstr "Vind"

#~ msgid "True Wind"
#~ msgstr "Ekte vind"

#~ msgid "Center"
#~ msgstr "Senter"

#~ msgid "&Scope"
#~ msgstr "&Omfang"

#~ msgid "&Client"
#~ msgstr "&Klient"

#~ msgid "C&alibration"
#~ msgstr "K&alibrering"

#~ msgid "Close"
#~ msgstr "Lukk"

#~ msgid "Calibration"
#~ msgstr "Kalibrering"

#~ msgid "Boat is level"
#~ msgstr "Båten er i vater"

#~ msgid "Reset"
#~ msgstr "Nullstille"

#~ msgid "Alignment"
#~ msgstr "Justering"

#~ msgid "Heading"
#~ msgstr "Overskrift"

#~ msgid "     N/A     "
#~ msgstr "Ikke relevant"

#~ msgid "Offset"
#~ msgstr "Offset"

#~ msgid "Coords"
#~ msgstr "Koordiner"

#~ msgid "Sea"
#~ msgstr "Hav"

#~ msgid "Boat"
#~ msgstr "Båt"

#~ msgid "Scope"
#~ msgstr "omfang"

#~ msgid "Pitch"
#~ msgstr "Tonehøyde"

#~ msgid "Roll"
#~ msgstr "Rull"

#~ msgid "Heel"
#~ msgstr "Hæl"

#~ msgid "alignment"
#~ msgstr "Justering"

#~ msgid "Calibration Age"
#~ msgstr "Kalibreringsalder"

#~ msgid "Clear"
#~ msgstr "Klar"

#~ msgid "calibration locked"
#~ msgstr "kalibrering låst"

#~ msgid "accel"
#~ msgstr "accelere"

#~ msgid "Sigma Points"
#~ msgstr "Sigma poeng"

#~ msgid "local history"
#~ msgstr "lokalhistorie"

#~ msgid "current"
#~ msgstr "nåværende"

#~ msgid "Calibration Points"
#~ msgstr "Kalibreringspunkter"

#~ msgid "compass"
#~ msgstr "kompass"

#~ msgid ""
#~ "Press each button when the rudder is at the correct position to calibrate."
#~ msgstr "Trykk på hver knapp når roret er i riktig posisjon for å kalibrere."

#~ msgid "Rudder"
#~ msgstr "Ror"

#~ msgid "Reset Calibration"
#~ msgstr "Tilbakestill kalibrering"

#~ msgid "Rudder Is Centered"
#~ msgstr "Ror er sentrert"

#~ msgid "------"
#~ msgstr "------"

#~ msgid "Rudder is Starboard Range"
#~ msgstr "Ror er styrbord"

#~ msgid "Scale"
#~ msgstr "Skala"

#~ msgid "Rudder is Port Range"
#~ msgstr "Ror er havneserie"

#~ msgid "Non Linearity"
#~ msgstr "Ikke lineæritet"

#~ msgid " range +-"
#~ msgstr "rekkevidde + -"

#~ msgid "degrees"
#~ msgstr "grader"

#~ msgid "rudder"
#~ msgstr "ror"

#~ msgid "settings"
#~ msgstr "innstillinger"

#~ msgid "failed to load pywavefront:"
#~ msgstr "mislyktes i å laste inn pywavefront:"

#~ msgid "invalid display dimensions"
#~ msgstr "ugyldige dimensjoner"

#~ msgid "Did you add the pypilot_data repository?"
#~ msgstr "Har du lagt til pypilot_data-depotet?"

#~ msgid "not found, texture compass cannot be used"
#~ msgstr "ikke funnet, teksturkompass kan ikke brukes"

#~ msgid "Refresh"
#~ msgstr "Forfriske"

#~ msgid "Connected"
#~ msgstr "Tilkoblet"

#~ msgid "Disconnected"
#~ msgstr "Frakoblet"

#~ msgid "warning, invalid choice value specified"
#~ msgstr "advarsel, ugyldig valgverdi spesifisert"

#~ msgid "pypilot Scope"
#~ msgstr "pypilot Omfang"

#~ msgid "Zero"
#~ msgstr "Null"

#~ msgid "Scale +"
#~ msgstr "Skala +"

#~ msgid "Scale -"
#~ msgstr "Skala -"

#~ msgid "Offset /\\"
#~ msgstr "Offset / \\"

#~ msgid "Offset \\/"
#~ msgstr "Offset \\ /"

#~ msgid "Freeze"
#~ msgstr "Fryse"

#~ msgid "fftw"
#~ msgstr "fftw"

#~ msgid "Time"
#~ msgstr "Tid"

#~ msgid "values not found:"
#~ msgstr "ikke funnet verdier:"

#~ msgid "in"
#~ msgstr "i"

#~ msgid "seconds"
#~ msgstr "sekunder"

#~ msgid "nmea client failed to connect to"
#~ msgstr "nmea-klienten kunne ikke koble til"

#~ msgid "failed to create nmea socket as host:port"
#~ msgstr "mislyktes i å opprette nmea-sokkel som vert: port"

#~ msgid "terminate calibration process"
#~ msgstr "avslutte kalibreringsprosessen"
